//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.81.0.
// 

namespace Roth.Touchline.API.YrModels
{



	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
	public partial class weatherdata
	{

		private metaType metaField;

		private productType[] productField;

		private System.DateTime createdField;

		/// <remarks/>
		public metaType meta
		{
			get
			{
				return this.metaField;
			}
			set
			{
				this.metaField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("product")]
		public productType[] product
		{
			get
			{
				return this.productField;
			}
			set
			{
				this.productField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public System.DateTime created
		{
			get
			{
				return this.createdField;
			}
			set
			{
				this.createdField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class metaType
	{

		private modelType[] modelField;

		private string licenseurlField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("model")]
		public modelType[] model
		{
			get
			{
				return this.modelField;
			}
			set
			{
				this.modelField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType = "anyURI")]
		public string licenseurl
		{
			get
			{
				return this.licenseurlField;
			}
			set
			{
				this.licenseurlField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class modelType
	{

		private string nameField;

		private string terminField;

		private string runendedField;

		private string nextrunField;

		private string fromField;

		private string toField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string name
		{
			get
			{
				return this.nameField;
			}
			set
			{
				this.nameField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string termin
		{
			get
			{
				return this.terminField;
			}
			set
			{
				this.terminField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string runended
		{
			get
			{
				return this.runendedField;
			}
			set
			{
				this.runendedField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string nextrun
		{
			get
			{
				return this.nextrunField;
			}
			set
			{
				this.nextrunField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string from
		{
			get
			{
				return this.fromField;
			}
			set
			{
				this.fromField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string to
		{
			get
			{
				return this.toField;
			}
			set
			{
				this.toField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class windspeed
	{

		private decimal mpsField;

		private string nameField;

		private string beaufortField;

		private string idField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public decimal mps
		{
			get
			{
				return this.mpsField;
			}
			set
			{
				this.mpsField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string name
		{
			get
			{
				return this.nameField;
			}
			set
			{
				this.nameField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
		public string beaufort
		{
			get
			{
				return this.beaufortField;
			}
			set
			{
				this.beaufortField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string id
		{
			get
			{
				return this.idField;
			}
			set
			{
				this.idField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class score
	{

		private string unitField;

		private string overallField;

		private string very_goodField;

		private string goodField;

		private string mediocreField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string unit
		{
			get
			{
				return this.unitField;
			}
			set
			{
				this.unitField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
		public string overall
		{
			get
			{
				return this.overallField;
			}
			set
			{
				this.overallField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
		public string very_good
		{
			get
			{
				return this.very_goodField;
			}
			set
			{
				this.very_goodField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
		public string good
		{
			get
			{
				return this.goodField;
			}
			set
			{
				this.goodField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
		public string mediocre
		{
			get
			{
				return this.mediocreField;
			}
			set
			{
				this.mediocreField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class tidalwater
	{

		private string unitField;

		private string tidalField;

		private string weathercorrectionField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string unit
		{
			get
			{
				return this.unitField;
			}
			set
			{
				this.unitField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
		public string tidal
		{
			get
			{
				return this.tidalField;
			}
			set
			{
				this.tidalField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
		public string weathercorrection
		{
			get
			{
				return this.weathercorrectionField;
			}
			set
			{
				this.weathercorrectionField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class unit_value
	{

		private string unitField;

		private float valueField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string unit
		{
			get
			{
				return this.unitField;
			}
			set
			{
				this.unitField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public float value
		{
			get
			{
				return this.valueField;
			}
			set
			{
				this.valueField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class uv
	{

		private unit_value uvi_clearField;

		private unit_value uvi_partly_cloudyField;

		private unit_value uvi_cloudyField;

		private unit_value uvi_forecastField;

		private unit_value ozonField;

		private unit_value snowcoverField;

		private unit_value cloudcoverField;

		private unit_value albedoField;

		private unit_value solar_zenithField;

		/// <remarks/>
		public unit_value uvi_clear
		{
			get
			{
				return this.uvi_clearField;
			}
			set
			{
				this.uvi_clearField = value;
			}
		}

		/// <remarks/>
		public unit_value uvi_partly_cloudy
		{
			get
			{
				return this.uvi_partly_cloudyField;
			}
			set
			{
				this.uvi_partly_cloudyField = value;
			}
		}

		/// <remarks/>
		public unit_value uvi_cloudy
		{
			get
			{
				return this.uvi_cloudyField;
			}
			set
			{
				this.uvi_cloudyField = value;
			}
		}

		/// <remarks/>
		public unit_value uvi_forecast
		{
			get
			{
				return this.uvi_forecastField;
			}
			set
			{
				this.uvi_forecastField = value;
			}
		}

		/// <remarks/>
		public unit_value ozon
		{
			get
			{
				return this.ozonField;
			}
			set
			{
				this.ozonField = value;
			}
		}

		/// <remarks/>
		public unit_value snowcover
		{
			get
			{
				return this.snowcoverField;
			}
			set
			{
				this.snowcoverField = value;
			}
		}

		/// <remarks/>
		public unit_value cloudcover
		{
			get
			{
				return this.cloudcoverField;
			}
			set
			{
				this.cloudcoverField = value;
			}
		}

		/// <remarks/>
		public unit_value albedo
		{
			get
			{
				return this.albedoField;
			}
			set
			{
				this.albedoField = value;
			}
		}

		/// <remarks/>
		public unit_value solar_zenith
		{
			get
			{
				return this.solar_zenithField;
			}
			set
			{
				this.solar_zenithField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class cloudiness
	{

		private string eightsField;

		private string percentField;

		private string idField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
		public string eights
		{
			get
			{
				return this.eightsField;
			}
			set
			{
				this.eightsField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string percent
		{
			get
			{
				return this.percentField;
			}
			set
			{
				this.percentField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string id
		{
			get
			{
				return this.idField;
			}
			set
			{
				this.idField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class temperature
	{

		private string unitField;

		private decimal valueField;

		private string idField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string unit
		{
			get
			{
				return this.unitField;
			}
			set
			{
				this.unitField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public decimal value
		{
			get
			{
				return this.valueField;
			}
			set
			{
				this.valueField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string id
		{
			get
			{
				return this.idField;
			}
			set
			{
				this.idField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class precipitation
	{

		private string unitField;

		private decimal valueField;

		private float minvalueField;

		private bool minvalueFieldSpecified;

		private float maxvalueField;

		private bool maxvalueFieldSpecified;

		private float probabilityField;

		private bool probabilityFieldSpecified;

		private string idField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string unit
		{
			get
			{
				return this.unitField;
			}
			set
			{
				this.unitField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public decimal value
		{
			get
			{
				return this.valueField;
			}
			set
			{
				this.valueField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public float minvalue
		{
			get
			{
				return this.minvalueField;
			}
			set
			{
				this.minvalueField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool minvalueSpecified
		{
			get
			{
				return this.minvalueFieldSpecified;
			}
			set
			{
				this.minvalueFieldSpecified = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public float maxvalue
		{
			get
			{
				return this.maxvalueField;
			}
			set
			{
				this.maxvalueField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool maxvalueSpecified
		{
			get
			{
				return this.maxvalueFieldSpecified;
			}
			set
			{
				this.maxvalueFieldSpecified = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public float probability
		{
			get
			{
				return this.probabilityField;
			}
			set
			{
				this.probabilityField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool probabilitySpecified
		{
			get
			{
				return this.probabilityFieldSpecified;
			}
			set
			{
				this.probabilityFieldSpecified = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string id
		{
			get
			{
				return this.idField;
			}
			set
			{
				this.idField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class pressure
	{

		private string unitField;

		private decimal valueField;

		private string idField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string unit
		{
			get
			{
				return this.unitField;
			}
			set
			{
				this.unitField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public decimal value
		{
			get
			{
				return this.valueField;
			}
			set
			{
				this.valueField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string id
		{
			get
			{
				return this.idField;
			}
			set
			{
				this.idField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class groundcover
	{

		private string numberField;

		private string nameField;

		private string idField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
		public string number
		{
			get
			{
				return this.numberField;
			}
			set
			{
				this.numberField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string name
		{
			get
			{
				return this.nameField;
			}
			set
			{
				this.nameField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string id
		{
			get
			{
				return this.idField;
			}
			set
			{
				this.idField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class locationType
	{

		private groundcover[] groundCoverField;

		private pressure[] pressureField;

		private precipitation[] maximumPrecipitationField;

		private temperature[] highestTemperatureField;

		private temperature[] lowestTemperatureField;

		private precipitation[] precipitationField;

		private cloudiness[] fogField;

		private cloudiness[] cloudinessField;

		private cloudiness[] lowCloudsField;

		private cloudiness[] mediumCloudsField;

		private cloudiness[] highCloudsField;

		private temperature[] temperatureField;

		private temperature[] dewpointTemperatureField;

		private temperature[] minTemperatureField;

		private temperature[] minTemperatureDayField;

		private temperature[] minTemperatureNightField;

		private temperature[] maxTemperatureField;

		private temperature[] maxTemperatureDayField;

		private temperature[] maxTemperatureNightField;

		private uv[] uvField;

		private tidalwater[] tidalwaterField;

		private unit_value[] currentDirectionField;

		private unit_value[] maxWaveHeightField;

		private unit_value[] surfaceTemperatureField;

		private unit_value[] waveDirectionField;

		private unit_value[] wavePeriodField;

		private unit_value[] waveHeightField;

		private unit_value[] humidityField;

		private unit_value[] biasField;

		private unit_value[] numberofobservationsField;

		private unit_value[] meanabsoluteerrorField;

		private score[] scoreField;

		private locationTypeWindDirection[] windDirectionField;

		private windspeed[] windSpeedField;

		private windspeed[] windGustField;

		private windspeed[] maxWindSpeedField;

		private locationTypeStateOfTheSea[] stateOfTheSeaField;

		private locationTypeSnowDepth[] snowDepthField;

		private locationTypeWeather[] weatherField;

		private locationTypeSymbol[] symbolField;

		private locationTypeForestfire[] forestfireField;

		private unit_value[] windProbabilityField;

		private unit_value[] temperatureProbabilityField;

		private unit_value[] symbolProbabilityField;

		private string idField;

		private string nameField;

		private string stationidField;

		private string countryField;

		private string countyField;

		private string latitudeField;

		private string longitudeField;

		private string altitudeField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("groundCover")]
		public groundcover[] groundCover
		{
			get
			{
				return this.groundCoverField;
			}
			set
			{
				this.groundCoverField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("pressure")]
		public pressure[] pressure
		{
			get
			{
				return this.pressureField;
			}
			set
			{
				this.pressureField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("maximumPrecipitation")]
		public precipitation[] maximumPrecipitation
		{
			get
			{
				return this.maximumPrecipitationField;
			}
			set
			{
				this.maximumPrecipitationField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("highestTemperature")]
		public temperature[] highestTemperature
		{
			get
			{
				return this.highestTemperatureField;
			}
			set
			{
				this.highestTemperatureField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("lowestTemperature")]
		public temperature[] lowestTemperature
		{
			get
			{
				return this.lowestTemperatureField;
			}
			set
			{
				this.lowestTemperatureField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("precipitation")]
		public precipitation[] precipitation
		{
			get
			{
				return this.precipitationField;
			}
			set
			{
				this.precipitationField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("fog")]
		public cloudiness[] fog
		{
			get
			{
				return this.fogField;
			}
			set
			{
				this.fogField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("cloudiness")]
		public cloudiness[] cloudiness
		{
			get
			{
				return this.cloudinessField;
			}
			set
			{
				this.cloudinessField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("lowClouds")]
		public cloudiness[] lowClouds
		{
			get
			{
				return this.lowCloudsField;
			}
			set
			{
				this.lowCloudsField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("mediumClouds")]
		public cloudiness[] mediumClouds
		{
			get
			{
				return this.mediumCloudsField;
			}
			set
			{
				this.mediumCloudsField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("highClouds")]
		public cloudiness[] highClouds
		{
			get
			{
				return this.highCloudsField;
			}
			set
			{
				this.highCloudsField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("temperature")]
		public temperature[] temperature
		{
			get
			{
				return this.temperatureField;
			}
			set
			{
				this.temperatureField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("dewpointTemperature")]
		public temperature[] dewpointTemperature
		{
			get
			{
				return this.dewpointTemperatureField;
			}
			set
			{
				this.dewpointTemperatureField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("minTemperature")]
		public temperature[] minTemperature
		{
			get
			{
				return this.minTemperatureField;
			}
			set
			{
				this.minTemperatureField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("minTemperatureDay")]
		public temperature[] minTemperatureDay
		{
			get
			{
				return this.minTemperatureDayField;
			}
			set
			{
				this.minTemperatureDayField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("minTemperatureNight")]
		public temperature[] minTemperatureNight
		{
			get
			{
				return this.minTemperatureNightField;
			}
			set
			{
				this.minTemperatureNightField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("maxTemperature")]
		public temperature[] maxTemperature
		{
			get
			{
				return this.maxTemperatureField;
			}
			set
			{
				this.maxTemperatureField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("maxTemperatureDay")]
		public temperature[] maxTemperatureDay
		{
			get
			{
				return this.maxTemperatureDayField;
			}
			set
			{
				this.maxTemperatureDayField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("maxTemperatureNight")]
		public temperature[] maxTemperatureNight
		{
			get
			{
				return this.maxTemperatureNightField;
			}
			set
			{
				this.maxTemperatureNightField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("uv")]
		public uv[] uv
		{
			get
			{
				return this.uvField;
			}
			set
			{
				this.uvField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("tidalwater")]
		public tidalwater[] tidalwater
		{
			get
			{
				return this.tidalwaterField;
			}
			set
			{
				this.tidalwaterField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("currentDirection")]
		public unit_value[] currentDirection
		{
			get
			{
				return this.currentDirectionField;
			}
			set
			{
				this.currentDirectionField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("maxWaveHeight")]
		public unit_value[] maxWaveHeight
		{
			get
			{
				return this.maxWaveHeightField;
			}
			set
			{
				this.maxWaveHeightField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("surfaceTemperature")]
		public unit_value[] surfaceTemperature
		{
			get
			{
				return this.surfaceTemperatureField;
			}
			set
			{
				this.surfaceTemperatureField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("waveDirection")]
		public unit_value[] waveDirection
		{
			get
			{
				return this.waveDirectionField;
			}
			set
			{
				this.waveDirectionField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("wavePeriod")]
		public unit_value[] wavePeriod
		{
			get
			{
				return this.wavePeriodField;
			}
			set
			{
				this.wavePeriodField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("waveHeight")]
		public unit_value[] waveHeight
		{
			get
			{
				return this.waveHeightField;
			}
			set
			{
				this.waveHeightField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("humidity")]
		public unit_value[] humidity
		{
			get
			{
				return this.humidityField;
			}
			set
			{
				this.humidityField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("bias")]
		public unit_value[] bias
		{
			get
			{
				return this.biasField;
			}
			set
			{
				this.biasField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("numberofobservations")]
		public unit_value[] numberofobservations
		{
			get
			{
				return this.numberofobservationsField;
			}
			set
			{
				this.numberofobservationsField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("meanabsoluteerror")]
		public unit_value[] meanabsoluteerror
		{
			get
			{
				return this.meanabsoluteerrorField;
			}
			set
			{
				this.meanabsoluteerrorField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("score")]
		public score[] score
		{
			get
			{
				return this.scoreField;
			}
			set
			{
				this.scoreField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("windDirection")]
		public locationTypeWindDirection[] windDirection
		{
			get
			{
				return this.windDirectionField;
			}
			set
			{
				this.windDirectionField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("windSpeed")]
		public windspeed[] windSpeed
		{
			get
			{
				return this.windSpeedField;
			}
			set
			{
				this.windSpeedField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("windGust")]
		public windspeed[] windGust
		{
			get
			{
				return this.windGustField;
			}
			set
			{
				this.windGustField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("maxWindSpeed")]
		public windspeed[] maxWindSpeed
		{
			get
			{
				return this.maxWindSpeedField;
			}
			set
			{
				this.maxWindSpeedField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("stateOfTheSea")]
		public locationTypeStateOfTheSea[] stateOfTheSea
		{
			get
			{
				return this.stateOfTheSeaField;
			}
			set
			{
				this.stateOfTheSeaField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("snowDepth")]
		public locationTypeSnowDepth[] snowDepth
		{
			get
			{
				return this.snowDepthField;
			}
			set
			{
				this.snowDepthField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("weather")]
		public locationTypeWeather[] weather
		{
			get
			{
				return this.weatherField;
			}
			set
			{
				this.weatherField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("symbol")]
		public locationTypeSymbol[] symbol
		{
			get
			{
				return this.symbolField;
			}
			set
			{
				this.symbolField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("forest-fire")]
		public locationTypeForestfire[] forestfire
		{
			get
			{
				return this.forestfireField;
			}
			set
			{
				this.forestfireField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("windProbability")]
		public unit_value[] windProbability
		{
			get
			{
				return this.windProbabilityField;
			}
			set
			{
				this.windProbabilityField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("temperatureProbability")]
		public unit_value[] temperatureProbability
		{
			get
			{
				return this.temperatureProbabilityField;
			}
			set
			{
				this.temperatureProbabilityField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("symbolProbability")]
		public unit_value[] symbolProbability
		{
			get
			{
				return this.symbolProbabilityField;
			}
			set
			{
				this.symbolProbabilityField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string id
		{
			get
			{
				return this.idField;
			}
			set
			{
				this.idField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string name
		{
			get
			{
				return this.nameField;
			}
			set
			{
				this.nameField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
		public string stationid
		{
			get
			{
				return this.stationidField;
			}
			set
			{
				this.stationidField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string country
		{
			get
			{
				return this.countryField;
			}
			set
			{
				this.countryField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string county
		{
			get
			{
				return this.countyField;
			}
			set
			{
				this.countyField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string latitude
		{
			get
			{
				return this.latitudeField;
			}
			set
			{
				this.latitudeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string longitude
		{
			get
			{
				return this.longitudeField;
			}
			set
			{
				this.longitudeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string altitude
		{
			get
			{
				return this.altitudeField;
			}
			set
			{
				this.altitudeField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class locationTypeWindDirection
	{

		private decimal degField;

		private string nameField;

		private string idField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public decimal deg
		{
			get
			{
				return this.degField;
			}
			set
			{
				this.degField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string name
		{
			get
			{
				return this.nameField;
			}
			set
			{
				this.nameField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string id
		{
			get
			{
				return this.idField;
			}
			set
			{
				this.idField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class locationTypeStateOfTheSea
	{

		private string numberField;

		private string meterField;

		private string nameField;

		private string idField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
		public string number
		{
			get
			{
				return this.numberField;
			}
			set
			{
				this.numberField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string meter
		{
			get
			{
				return this.meterField;
			}
			set
			{
				this.meterField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string name
		{
			get
			{
				return this.nameField;
			}
			set
			{
				this.nameField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string id
		{
			get
			{
				return this.idField;
			}
			set
			{
				this.idField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class locationTypeSnowDepth
	{

		private decimal cmField;

		private string idField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public decimal cm
		{
			get
			{
				return this.cmField;
			}
			set
			{
				this.cmField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string id
		{
			get
			{
				return this.idField;
			}
			set
			{
				this.idField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class locationTypeWeather
	{

		private string nameField;

		private string numberField;

		private string idField;

		private string symbolField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string name
		{
			get
			{
				return this.nameField;
			}
			set
			{
				this.nameField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
		public string number
		{
			get
			{
				return this.numberField;
			}
			set
			{
				this.numberField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string id
		{
			get
			{
				return this.idField;
			}
			set
			{
				this.idField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
		public string symbol
		{
			get
			{
				return this.symbolField;
			}
			set
			{
				this.symbolField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class locationTypeSymbol
	{

		private string idField;

		private string nameField;

		private string numberField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string id
		{
			get
			{
				return this.idField;
			}
			set
			{
				this.idField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string name
		{
			get
			{
				return this.nameField;
			}
			set
			{
				this.nameField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
		public string number
		{
			get
			{
				return this.numberField;
			}
			set
			{
				this.numberField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class locationTypeForestfire
	{

		private string unitField;

		private string valueField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string unit
		{
			get
			{
				return this.unitField;
			}
			set
			{
				this.unitField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string value
		{
			get
			{
				return this.valueField;
			}
			set
			{
				this.valueField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class timeType
	{

		private locationType[] locationField;

		private System.DateTime fromField;

		private System.DateTime toField;

		private timeTypeDatatype datatypeField;

		private bool datatypeFieldSpecified;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("location")]
		public locationType[] location
		{
			get
			{
				return this.locationField;
			}
			set
			{
				this.locationField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public System.DateTime from
		{
			get
			{
				return this.fromField;
			}
			set
			{
				this.fromField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public System.DateTime to
		{
			get
			{
				return this.toField;
			}
			set
			{
				this.toField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public timeTypeDatatype datatype
		{
			get
			{
				return this.datatypeField;
			}
			set
			{
				this.datatypeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool datatypeSpecified
		{
			get
			{
				return this.datatypeFieldSpecified;
			}
			set
			{
				this.datatypeFieldSpecified = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public enum timeTypeDatatype
	{

		/// <remarks/>
		observation,

		/// <remarks/>
		forecast,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class productType
	{

		private timeType[] timeField;

		private productTypeClass classField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("time")]
		public timeType[] time
		{
			get
			{
				return this.timeField;
			}
			set
			{
				this.timeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public productTypeClass @class
		{
			get
			{
				return this.classField;
			}
			set
			{
				this.classField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public enum productTypeClass
	{

		/// <remarks/>
		pointData,

		/// <remarks/>
		extremes,

		/// <remarks/>
		forestfireindex,

		/// <remarks/>
		uvforecast,

		/// <remarks/>
		tidalwater,

		/// <remarks/>
		buoy,

		/// <remarks/>
		stavernodden,

		/// <remarks/>
		seaapproachforecast,

		/// <remarks/>
		temperatureverification,
	}
}